### ISSUE TITLE
Unused callback in example code

### ISSUE THREAD

**Issue by kalj** [rppicomidi/usb_midi_host#16]
This callback doesn't seem to be good for anything?

https://github.com/rppicomidi/usb_midi_host/blob/a64d35d4879da0d1dc2fe30ec3b6f43bd47ec9bc/examples/arduino/usb_midi_host_example/usb_midi_host_example.ino#L278

**Comment by rppicomidi** [comment]
You are correct. That callback is a debug artifact that I should have deleted. I will update my code. Thank you for taking the time to report the issue.
